server:
  port: 8083
  context-path: /

spring:
  application:
    name: commodity-service

  cloud:
    consul:
      ##注册中心ip地址
      host: 192.168.1.7
      ##注册中心监听端口
      port: 8500
      discovery:
        register: true
        ##商品微服务实例id
        instance-id: commodity-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3306/db_commodity?useSSL=false
    username: root
    password: root
    ##初始化连接数
    initialSize: 5
    ##最小连接数
    minIdle: 5
    ##最大连接数
    maxActive: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  health:
    consul:
      enabled: false
